### ISSUE TITLE
Retrieve CIOOS Metadata form associated to a CKAN record 

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/metadata-entry-form#256]
It would be great for some applications to be able to link the CKAN record to its associated metadata form.

This would help testing metadata synchronization between the different resources associated with a CKAN record and refer back to the form if there's some issues. 

In my use case, I'd like to compare ERDDAP metadata associated to a cioos metadata/ckan record et retrieve back the ERDDAP xml conversion from the metadata form if some differences are detected.

**Comment by fostermh** [comment]
are you wanting to link from an erddap record to a ckan record or from erddap to a metadata form entry and from there to ckan?

the xml output from the form contains `Generated from https://cioos-siooc.github.io/metadata-entry-form` which we could perhaps expand to include the fill path to the form. the problem is that this is tied to a user so if the record is transfered to another user the link would break. not sure if that ever happens though.

**Comment by JessyBarrette** [comment]
ideally 
>  from erddap to a metadata form entry and from there to ckan


> we could perhaps expand to include the fill path to the form

This would be perfect 

> the problem is that this is tied to a user so if the record is transfered to another user the link would break. not sure if that ever happens though.

Hum I've done that myself in the past. I could see that in future has projects gets transfered to another party/person to become an issue

**Comment by fostermh** [comment]
TODO: Extend 'Generated from https://cioos-siooc.github.io/metadata-entry-form' to include the full link to the metadata form entry
